WebUI/BlogAdsense.Snapyfox/Models/ContentViewModel.cs
namespace BlogAdsense.Snapyfox.Models
{
    using BlogAdsense.Model;
    using System.Collections.Generic;

    public class ContentViewModel
    {
        public ContentViewModel()
        {
            RelatedContent = new List<Content>();
        }

        public List<Content> RelatedContent { get; set; }
        public Content Content { get; set; }
        public List<string> ImgScrs { get; set; }
    }
}

WebUI/BlogAdsense.Snapyfox/Controllers/CategoryController.cs
namespace BlogAdsense.Snapyfox.Controllers
{
    using BlogAdsense.Data;
    using BlogAdsense.Model;
    using BlogAdsense.Snapyfox.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class CategoryController : Controller
    {
        CategoryData _categoryData;
        ContentData _contentData;

        public CategoryController()
        {
            _categoryData = new CategoryData();
            _contentData = new ContentData();
        }

        public ActionResult Index()
        {
            var categories = _categoryData.GetAll();
            var model = new CategoryViewModel()
            {
                CategoryList = categories,
            };

            return View(model);
        }

        public ActionResult Detail(string slug, int page = 1)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Error", "Home", new { e = "no-slug" });

            var category = _categoryData.GetBy(x => x.Slug == slug).FirstOrDefault();
            if (category == null)
                return RedirectToAction("Error", "Home", new { e = "category-not-found" });

            int _pageSize = 15;

            var contents = _contentData.GetByPage(x => x.CategoryId == category.Id,page, _pageSize, "Id",true);
            var count = _contentData.GetCount(x => x.CategoryId == category.Id);

            var model = new CategoryDetailViewModel()
            {
                Contents = contents,
                Category = category,
                TotalPageCount = (int)(count / _pageSize),
                CurrentPage = page
        };

            return View(model);
        }
    }
}

WebUI/BlogAdsense.Snapyfox/Controllers/ContentController.cs
namespace BlogAdsense.Snapyfox.Controllers
{
    using BlogAdsense.Data;
    using BlogAdsense.Snapyfox.Models;
    using HtmlAgilityPack;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text.RegularExpressions;
    using System.Web;
    using System.Web.Mvc;

    public class ContentController : Controller
    {
        ContentData _contentData;

        public ContentController()
        {
            _contentData = new ContentData();
        }

        public ActionResult Index(string slug)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Error", "Home", new { t = "no-slug" });

            var content = _contentData.GetBy(x => x.Slug == slug && x.IsActive).LastOrDefault();

            if (content == null)
                return View("Error", "Home", new { e = "not-found-content" });

            var related = _contentData.GetRandom(x => x.CategoryId == content.CategoryId, 3);

            var model = new ContentViewModel
            {
                Content = content,
                RelatedContent = related
            };

            return View(model);
        }

        public ActionResult Amp(string slug)
        {
            if (string.IsNullOrEmpty(slug))
                return RedirectToAction("Error", "Home", new { t = "no-slug" });

            var content = _contentData.GetBy(x=>x.Slug == slug && x.IsActive).LastOrDefault();

            if (content == null)
                return View("Error","Home", new { e = "not-found-content" });

            var related = _contentData.GetRandom(x => x.CategoryId == content.CategoryId, 4);

            var model = new ContentViewModel
            {
                Content = content,
                RelatedContent = related,
                ImgScrs = new List<string>()
            };

            HtmlDocument doc = new HtmlDocument();
            doc.LoadHtml(content.Description);
            var nodes = doc.DocumentNode.SelectNodes(@"//img[@src]");
            if (nodes != null)
            {
                foreach (var img in nodes)
                {
                    if (img.Attributes != null)
                    {
                        if (!string.IsNullOrEmpty(img.Attributes[0].Value)) { model.ImgScrs.Add(img.Attributes[0].Value); }
                        
                    }
                }
            }

            string description = content.Description;
            string image = Regex.Replace(description, @"<img\s[^>]*>(?:\s*?</img>)?", "", RegexOptions.IgnoreCase);
            image = Regex.Replace(image, @"<video\s[^>]*>(?:\s*?</video>)?", "", RegexOptions.IgnoreCase);
            ViewBag.Aciklama = image;

            return View(model);
        }
    }
}

WebUI/BlogAdsense.Snapyfox/Views/Content/Amp.cshtml
@model ContentViewModel
@{
    Layout = null;
    ViewBag.Title = Html.Raw(Model.Content.MetaTitle);
    ViewBag.Description = Html.Raw(Model.Content.MetaDescription);
    ViewBag.Robots = "index,follow";
    var videoReplace = ViewBag.Aciklama.Replace("<video", "<amp-video").Replace("</video>", "</amp-video>");
    var yazi = videoReplace;
    var url = CacheHelper.Settings.SiteAdress;
}

<!doctype html>
<html amp lang="tr">
<head>
    <meta charset="utf-8">
    <title>@Html.Raw(ViewBag.Title)</title>
    <link rel="canonical" href="@ViewBag.AmpCanonical">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&amp;subset=latin-ext">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <meta name="description" content="@Html.Raw(ViewBag.Description)" />
    <script type="application/ld+json">
    {
        "@@context": "http://schema.org",
        "@@type": "NewsArticle",
        "headline": "@Model.Content.Title",
        "mainEntityOfPage": "@ViewBag.AmpCanonical",
        "datePublished": "@Model.Content.PublishDate.ToString("yyyy-MM-ddTHH:mm:ss+0fff")",
        "dateModified": "@Model.Content.UpdateDate.ToString("yyyy-MM-ddTHH:mm:ss")",
        "description": "@Html.Raw(yazi)",
        "author": {
            "@@type": "Person",
            "name": "@CacheHelper.Settings.Sitename"
            },
        "publisher": {
            "@@type": "Organization",
            "name": "@CacheHelper.Settings.Sitename",
            "logo": {
                "@@type": "ImageObject",
                "url": "@Html.Raw(CacheHelper.Settings.SiteAdress+"/_assets/img/amp-logo.jpg")",
            "name": "youvolume"
            },
        "publisher": {
            "@@type": "Organization",
            "name": "youvolume",
            "logo": {
                "@@type": "ImageObject",
                "url": "@Html.Raw(CacheHelper.Settings.SiteAdress+"/_assets/img/amp-logo.jpg")",
                "width": 344,
                "height": 60
            }
        },
        "image": [
            "@url@Model.Content.ImagePath"
        ]
    }
    </script>

    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-video" src="https://cdn.ampproject.org/v0/amp-video-0.1.js"></script>

    <style amp-custom>
      body {font-family: 'Roboto';}
      header{width:100%;height:60px;position:fixed;background-color:#A40000;top:0;z-index:5;line-height:60px;}
      header .logo{width:50%;box-sizing:border-box;padding:0 5px;margin-top:10px;float:left;height:50px;background:transparent;}
      header a {float:right;box-sizing:border-box;width:50%;padding-right:10px;font-size:14px;text-decoration:none;color:#fff;text-align:right;}
      header::after{content:"";display:table;clear:both;}
      .amp-content{margin-top:75px;}
      amp-video{margin:10px 0;}
      h1{font-size:20px;width:100%;box-sizing:border-box;padding:0 15px;color:#333;}
      .postDescription{width:100%; box-sizing:border-box;padding:0 15px;}
      .postDescription amp-img{margin:5px 0;}
      .postDescription p{margin:5px 0; font-size:14px;}
      h2,h3,h4,h5,h6{font-size:16px; color:#333; width:100%; border-bottom:1px solid #dedede; margin:5px 0; padding-bottom:5px; font-weight:500;}
      .otherPost{width:100%; box-sizing:border-box; padding:0 15px;}
      .otherPost h2{margin:10px auto;}
      .relatedItem{width:100%; box-sizing:border-box; height:70px; margin-bottom:10px; overflow:hidden;}
      .relatedItem amp-img{float:left; width:30%; margin-right:7px;}
      .relatedItem h6{border:none; padding:0; margin:0; height:70px;}
      .relatedTitle a{text-decoration:none; font-size:14px; color:#000; display:block; height:70px; line-height:17px; font-weight:500;}
    </style>

</head>
<body>
    <header>
        <div class="logo">
            <amp-img
                src="@Html.Raw(CacheHelper.Settings.SiteAdress + "/_assets/img/amp-header-logo.png")"
                alt="@CacheHelper.Settings.Sitename technology news"
                width="100"
                height="40">
            </amp-img>
        </div>
        <a href="@Url.Action("Index","Category", new { slug = Model.Content.Category.Slug })" title="youvolume @Model.Content.Category.Title Category related article">
            More Articles...
        </a>
    </header>
    <div class="amp-content">
        <div class="hidden">@Model.Content.Category.Title</div>
        <h1 >@Model.Content.Title</h1>
        <amp-img 
            src="@Model.Content.ImagePath" 
            alt="@Model.Content.Title" 
            layout="responsive"
            title="@Model.Content.Title" 
            width="1040" 
            height="693">
        </amp-img>
        <div class="postDescription">
            @if (!string.IsNullOrEmpty(ViewBag.VideoAddress))
            {
                <amp-video 
                    width="480"
                    height="270"
                    src="@ViewBag.VideoAddress"
                    poster="@Model.Content.ImagePath"
                    layout="responsive"
                    controls>
                        <div fallback>
                            <p>Tarayıcınız Video Oynatıcısını Desteklemiyor</p>
                        </div>
                        <source type="video/webm"
                            src="@ViewBag.VideoAddress">
                    </amp-video>
            }

            <p itemprop="articleBody">@Html.Raw(yazi)</p>
            @foreach (var item in Model.ImgScrs)
            {
                <amp-img itemprop="image"
                    src="@item"
                    layout="responsive"
                    title="@Model.Content.Title"
                    width="420"
                    height="280">
                </amp-img>
            }
        </div>
        <div class="otherPost">
            <h2>Related Articles</h2>
            @foreach (var item in Model.RelatedContent)
            {
            <div class="relatedItem">
                <a href="@Url.Action("Index", "Content", new { slug = item.Slug })" title="@item.MetaTitle">
                    <amp-img 
                        src="@item.ImagePath" 
                        alt="@item.Title" 
                        layout="responsive"
                        title="@item.Title" 
                        width="1040" 
                        height="693">
                    </amp-img>
                </a>
                <h6 class="relatedTitle">
                    <a href="@Url.Action("Index", "Content", new { slug = item.Slug })" title="@item.MetaTitle">@item.Title</a>
                </h6>
            </div>
            }
        </div>
    </div>
</body>
</html>

WebUI/BlogAdsense.Snapyfox/Views/Content/Index.cshtml
@model ContentViewModel
@{
    ViewBag.Title = Model.Content.MetaTitle;
    ViewBag.Description = Model.Content.MetaDescription;
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Canonical = Url.Action("Index","Content", new { slug = Model.Content.Slug });
    ViewBag.Robots = "index,follow";
    ViewBag.SiteUrl = CacheHelper.Settings.SiteAdress;
    ViewBag.AmpCanonical = Url.Action("Amp", "Content", new { slug = Model.Content.Slug });
}

<div class="sp-page-title">
    <div class="container">
        <ol class="breadcrumb" itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
            <li class="here" data-s=">"><span>You are here:</span></li>
            <li data-s=">"><a itemprop="url" href="@Url.Action("Index","Home")" class="pathway">Home</a></li>
            <li data-s=">"><a itemprop="url" href="@Url.Action("Detail","Category", new { slug = Model.Content.Category.Slug })" class="pathway">@Model.Content.Category.Title</a></li>
            <li data-s=">" itemprop="title" class="active">@Model.Content.Title</li>
        </ol>
    </div>
</div>

<div id="sp-main-body">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <article class="sppb-addon-feature icon-mid" role="main" itemscope itemtype="http://schema.org/NewsArticle" data-type="news" data-url="@ViewBag.Canonical" data-title="@Model.Content.Title" data-description="@Model.Content.MetaDescription" data-keywords="@Model.Content.Keywords" data-share="0" data-amp="@ViewBag.AmpCanonical">
                    <meta itemprop="mainEntityOfPage" content="@ViewBag.Canonical" />
                    <meta itemprop="dateModified" content="@Model.Content.UpdateDate.ToString("yyyy-MM-ddTHH:mm:ss")" />
                    <meta itemprop="inLanguage" content="tr-TR" />
                    <meta itemprop="genre" content="news" name="medium" />
                    <h1 class="sppb-addon-title h1" itemprop="headline">@Model.Content.Title</h1>
                    <div class="meta">
                        <span class="author" itemprop="author" itemscope itemtype="http://schema.org/Person">by <span itemprop="name">@Model.Content.User.Fullname</span></span>
                        <time class="date" itemprop="datePublished" datetime="@Model.Content.CreateDate.ToString("yyyy-MM-ddTHH:mm:ss+0fff")">@Model.Content.CreateDate.ToString("dd MMMM yyyy")</time>
                        <span class="cate">in <a href="@Url.Action("Detail","Category", new { slug = Model.Content.Category.Slug })">@Model.Content.Category.Title</a></span>
                    </div>
                    <div class="sppb-image">
                        <figure itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
                            <img src="@Model.Content.ImagePath" alt="@Model.Content.MetaTitle" title="@Model.Content.MetaTitle" class="img-responsive post-thumb img-fitw" />
                            <meta itemprop="url" content="@ViewBag.SiteUrl@Model.Content.ImagePath" />
                            <meta itemprop="width" content="740" />
                            <meta itemprop="height" content="350" />
                        </figure>
                    </div>
                    <div class="sppb-addon-content">
                        <div class="sppb-addon-text" itemprop="description">
                            @Html.Raw(Model.Content.Description)
                        </div>
                    </div>
                    <div itemprop="publisher" itemscope itemtype="https://schema.org/Organization">
                        <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
                            <meta itemprop="url" content="@Html.Raw(CacheHelper.Settings.SiteAdress+"/_assets/img/icon-logo.jpg")" />
                            <meta itemprop="width" content="256" />
                            <meta itemprop="height" content="256" />
                        </div>
                        <meta itemprop="name" content="@CacheHelper.Settings.Sitename" />
                        <meta itemprop="url" content="@Html.Raw(CacheHelper.Settings.SiteAdress+"/_assets/img/icon-logo.jpg")" />
                        <meta itemprop="width" content="256" />
                        <meta itemprop="height" content="256" />
                    </div>
                    <meta itemprop="name" content="youvolume" />
                    <meta itemprop="sameAs" content="http://www.facebook.com" />
                </article>

                <div id="related" class="sppb-section">
                    <div class="sppb-section-title">
                        <h4>You May Also <strong>Like</strong></h4>
                    </div>
                    <div class="row">
                        @foreach (var item in Model.RelatedContent)
                        {
                            <div class="col-md-4 col-sm-4">
                                <div class="sppb-addon-feature mb30-xs wow fadeInRight">
                                    <img src="@item.ImagePath" alt="@item.MetaTitle" title="@item.MetaTitle" class="img-responsive post-thumb img-fitw">
                                    <div class="sppb-addon-content">
                                        <a href="@Url.Action("Index","Content", new { slug = item.Slug })"><h4 class="sppb-addon-title">@item.Title</h4></a>
                                        <div class="meta">
                                            <span class="author">by Alan Pandew</span>
                                            <span class="date">@item.CreateDate.ToString("dd MMMM yyyy")</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            @Html.Partial("_Sidebar")
        </div>
    </div>
</div>